export async function onRequestPost({ request, env }) {
  try {
    const body = await request.json();
    const GEMINI_API_KEY = env.GEMINI_API_KEY;

    if (!GEMINI_API_KEY) {
      return new Response(JSON.stringify({ error: "Gemini API key is not configured in Cloudflare environment." }), { status: 500 });
    }

    // Fetch the rules txt file from the same domain
    const url = new URL(request.url);
    const rulesUrl = `${url.protocol}//${url.host}/kepco_rules.txt`;
    
    let rulesText = "지장전주 업무기준 텍스트를 불러올 수 없습니다. 텍스트 파일 위치를 확인하세요.";
    try {
      const resp = await fetch(rulesUrl);
      if(resp.ok) rulesText = await resp.text();
    } catch(e) {
      console.error(e);
    }

    const systemInstruction = `
공식 직급: 한국전력공사(KEPCO) 지장전주 이설 비용 부담주체 판정 위원회 전문 매니저

가이드라인:
- 당신은 제공된 [배전선로 이설 업무기준] 및 [판례 데이터]를 기반으로 비용 부담주체를 판정하는 최고의 전문가입니다.
- 답변은 반드시 정해진 [보고서 형식]에 따라 매우 전문적이고 엄격한 문체로 작성하십시오.
- 규정에 근거가 명확하지 않은 경우, "추가 검토 필요"로 분류하고 필요한 서류를 요청하십시오.
- 환상을 배제하고 오직 문서 내용만 인용하십시오.

[보고서 형식]
1. 판정 개요: 신청 사유 및 현장 상황 요약
2. 관련 근거: [업무기준 제N조 N항] 원문 인용 및 해석
3. 판정 결과: 비용 부담주체 (한전/고객/공동 등) 명시
4. 판단 사유: 판정 결과에 대한 상세 논리적 근거
5. 추가 안내: 필요 시 구비 서류 또는 후속 조치 안내

=============================
[배전선로 이설 업무기준 및 판례 데이터]
${rulesText}
=============================
`;

    // Make request to Gemini REST API with retry logic
    const modelName = "gemini-2.5-flash"; // 보다 안정적인 모델명으로 변경
    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${GEMINI_API_KEY}`;
    
    const contents = body.messages.map(m => ({
      role: m.role === 'user' ? 'user' : 'model',
      parts: [{ text: m.content }]
    }));

    const payload = {
      system_instruction: { parts: [{ text: systemInstruction }] },
      contents: contents,
      generationConfig: {
        temperature: 0.1
      }
    };

    let attempts = 0;
    const maxAttempts = 3;
    let geminiResp;
    let data;

    while (attempts < maxAttempts) {
      attempts++;
      geminiResp = await fetch(geminiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });

      data = await geminiResp.json();

      if (geminiResp.ok && !data.error) break;

      // 429(Rate Limit)나 503(Service Unavailable)일 경우 재시도
      if (attempts < maxAttempts && (geminiResp.status === 429 || geminiResp.status === 503)) {
        const delay = Math.pow(2, attempts) * 1000;
        await new Promise(resolve => setTimeout(resolve, delay));
        continue;
      }

      // 그 외의 에러는 루프 종료 후 반환
      return new Response(JSON.stringify({ 
        error: data.error?.message || `Gemini API Error (Status ${geminiResp.status})` 
      }), { status: 500 });
    }

    if (!data.candidates || !data.candidates[0].content) {
      return new Response(JSON.stringify({ error: "No response from Gemini" }), { status: 500 });
    }

    const answer = data.candidates[0].content.parts[0].text;
    
    // 이메일 자동 발송 (Resend API)
    try {
      const resendApiKey = env.RESEND_API_KEY;
      
      if (!resendApiKey) {
        console.warn("이메일 발송 경고: RESEND_API_KEY 환경 변수가 설정되지 않았습니다.");
      }

      const receiptNumber = body.receiptNumber || "확인불가";
      
      const emailHtml = `
        <div style="font-family: 'Malgun Gothic', sans-serif; color: #334155; max-width: 650px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
          <div style="background-color: #2563eb; color: white; padding: 24px; text-align: center;">
            <h2 style="margin: 0; font-size: 24px;">지장전주 AI 판정 보고서</h2>
            <p style="margin: 8px 0 0 0; opacity: 0.9; font-size: 14px;">접수번호: <strong>${receiptNumber}</strong></p>
          </div>
          <div style="padding: 32px;">
            <div style="background-color: #f8fafc; padding: 24px; border-radius: 8px; margin-bottom: 24px; line-height: 1.7; font-size: 14px;">
              ${answer.replace(/\n/g, '<br>')}
            </div>
            <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
            <p style="font-size: 12px; color: #94a3b8; text-align: center; margin: 0;">
              본 메일은 KEPCO 지장주 판정시스템에서 자동 발송된 메일입니다.<br />
              Generated by KEPCO AI Engine
            </p>
          </div>
        </div>
      `;

      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${resendApiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          from: "onboarding@resend.dev",
          to: ["jihooncha09@kepco.co.kr", "waterking222@kepco.co.kr"],
          subject: `[지장전주 AI 판정 보고서] 접수번호: ${receiptNumber}`,
          html: emailHtml
        })
      });
    } catch (emailErr) {
      console.error("이메일 발송 실패:", emailErr);
      // 이메일 전송에 실패해도 사용자 화면에는 판정 결과가 정상적으로 표시되도록 에러를 무시합니다.
    }

    return new Response(JSON.stringify({ answer }), {
      headers: { "Content-Type": "application/json" }
    });

  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500 });
  }
}
